Merchantstuff2
BoHBranch/BoH-Bay pull request #1191
Opened 2022-02-13 23:06 UTC by Spummm

Git user: Spummm
Discord/ckey: Spum
Changes:
Moved merchant station powerloader so it will stop dying to simplemobs
Energy weapons are now worth MUCH more
Removed useless wizard trader that only buys wizard items
Modified animal trader so buying certain animals actually works now
Added several additional items that can be sold by diona and history merchant
Added the ability to buy random seeds from ONE trader that doesn't always show up
Modified other two food traders, one sells (most) drinks, the other sells (most) food items
Added some additional items to AI merchants

2022-02-13 23:48 UTC, Spummm commented
This still compiles, runs, and works as intended.

2022-02-14 01:01 UTC, Kaksisilma requested changes
Still gonna ask for @Yawet330 to take a look at the worths_list changes since I'm not sure what impact they'll have.

2022-02-14 01:01 UTC, Kaksisilma commented on maps/torch/z1_admin.dmm
> +	health = 1000;
```suggestion

```

2022-02-14 01:01 UTC, Kaksisilma commented on maps/torch/z1_admin.dmm
> +	maxHealth = 1000
```suggestion

```

2022-02-14 23:31 UTC, merged