Sol Gov Representative & Corp Rep Removal
BoHBranch/BoH-Bay pull request #1206
Opened 2022-02-15 20:59 UTC by Mannybrado

Reimplements Sol Gov Representative.
It has two alt-titles, Diplomat and Negotiator.
They are basically the supreme law without the ability to enforce it. When the Captain does something bad, this guy is the guy you go to. Otherwise, you now have a job to play when you want to slap people for acting like teenagers aboard the ship or to be a sleazy shithead and go "no!" with your suit jacket.

![image](https://user-images.githubusercontent.com/54787585/154148055-723316d8-0c16-4ce8-a7ce-cc8f448afdda.png)
oh yeah baby. (i've since added a solgov table flag on the table and a big one behind them)
Disables Corporate Representative and their bodyguard. The CR's room is now the Rep's room, changed up a small bit.
Finally, disables symbiote from the job list, finally.
TM first please

2022-02-15 23:17 UTC, Mannybrado commented
corp rep re-enabled. did you know they never spawned in their office? i never thought about that when i mained APA. oh well!

2022-02-16 00:16 UTC, Kaksisilma requested changes
Though I don't mind the addition of this new role, currently this feels a little too much like CO 2.0

Also what's up with the APA removal?

2022-02-16 00:16 UTC, Kaksisilma commented on code/game/objects/items/weapons/cards_ids.dm
> -/obj/item/weapon/card/id/civilian/head //This is not the HoP. There's no position that uses this right now.
This is clearer. I suggest keeping it if this goes through.

2022-02-16 00:16 UTC, Kaksisilma commented on maps/torch/job/command_jobs.dm
> +	department_flag = COM
```suggestion
	department_flag = SPT
```

2022-02-16 00:16 UTC, Kaksisilma commented on maps/torch/job/command_jobs.dm
> +	department = "Command"
```suggestion
	department = "Support"
```

2022-02-16 00:16 UTC, Kaksisilma commented on maps/torch/job/command_jobs.dm
> +	economic_power = 20
```suggestion
	economic_power = 16 // same as commanding officer's
```

2022-02-16 00:16 UTC, Kaksisilma commented on maps/torch/job/command_jobs.dm
> +	access = list(access_adjudicator, access_security, access_brig, access_forensics_lockers, access_heads, access_medical, access_morgue,
Hard no on this absurd amount of access. Here's a suggestion:
access = list(
		access_representative, access_security, access_medical,
		access_bridge, access_cargo, access_solgov_crew,
		access_hangar, access_torch_fax
	)

2022-02-16 00:16 UTC, Kaksisilma commented on maps/torch/job/command_jobs.dm
> +	return "You are the Sol Gov Representative. You are subordinate only to Central Command. Your job is represent the interests of the Solarian Central Government, to maintain said interests, and to ch
I feel like this is a less aggressive blurb. Keep in mind that they are a representative and a bureaucrat, not a Chief of Security. This is supposed to be a RP role more than anything.
```suggestion
	return "You are the Sol Gov Representative. You are a civilian assigned as both a diplomatic liaison for first contact and foreign affair situations on board. You are also responsible for monitoring for any serious missteps of justice, sol law or other ethical or legal issues aboard and informing and advising the Commanding Officer of them. You are a mid-level bureaucrat. You liaise between the crew and governmental interests on board. Send faxes back to Sol on mission progress and important events."
```

2022-02-16 00:16 UTC, Kaksisilma commented on maps/torch/job/corporate_jobs.dm
> +	total_positions = 0
Not sure what the consensus is on removing those so I'll refrain from commenting, though expect it to probably change.

2022-02-16 00:16 UTC, Kaksisilma commented on maps/torch/job/outfits/command_outfits.dm
> +	l_ear = /obj/item/device/radio/headset/heads/torchexec
```suggestion
	l_ear = /obj/item/device/radio/headset/bridgeofficer
```

2022-02-16 00:16 UTC, Kaksisilma commented on maps/torch/torch_areas.dm
>  /area/crew_quarters/heads/office/vip
If this is now an unused area, it can (should) be deleted.

2022-02-16 00:26 UTC, Kaksisilma commented
Feels like it would be better to just re-convert the VIP Room back to the Sol Rep's room aswell, honestly, though IDK Carl's take on this.

2022-02-16 04:03 UTC, Mannybrado commented
I'll fix this stuff tomorrow.

2022-02-16 05:34 UTC, ProbablyCarl commented
> Feels like it would be better to just re-convert the VIP Room back to the Sol Rep's room aswell, honestly, though IDK Carl's take on this.

Of the same mind. Retain CL for the moment, move SGRep back into their old office.

2022-02-16 05:34 UTC, ProbablyCarl commented
CL Rep removal can happen in a future PR. Would rather it be separate from the one reintroducing the SGRep.

2022-02-16 19:31 UTC, Yawet330 commented
Dunno why we're removing APA instead of shifting it to the SGR.

2022-02-16 20:46 UTC, Mannybrado commented on code/game/objects/items/weapons/cards_ids.dm
> -/obj/item/weapon/card/id/civilian/head //This is not the HoP. There's no position that uses this right now.
done

2022-02-16 20:46 UTC, Mannybrado commented on maps/torch/job/command_jobs.dm
> +	department_flag = COM
done

2022-02-16 20:46 UTC, Mannybrado commented on maps/torch/job/command_jobs.dm
> +	department = "Command"
done

2022-02-16 20:46 UTC, Mannybrado commented on maps/torch/job/command_jobs.dm
> +	economic_power = 20
done

2022-02-16 20:46 UTC, Mannybrado commented on maps/torch/job/command_jobs.dm
> +	access = list(access_adjudicator, access_security, access_brig, access_forensics_lockers, access_heads, access_medical, access_morgue,
Cut it down significantly. They still have a little bit more but, for instance, its still less than a BO.

2022-02-16 20:47 UTC, Mannybrado commented on maps/torch/job/command_jobs.dm
> +	return "You are the Sol Gov Representative. You are subordinate only to Central Command. Your job is represent the interests of the Solarian Central Government, to maintain said interests, and to ch
yeah... that's better. done.

2022-02-16 20:47 UTC, Mannybrado commented on maps/torch/job/outfits/command_outfits.dm
> +	l_ear = /obj/item/device/radio/headset/heads/torchexec
done.

2022-02-16 20:47 UTC, Mannybrado commented on maps/torch/torch_areas.dm
>  /area/crew_quarters/heads/office/vip
done.

2022-02-17 00:56 UTC, Mannybrado commented on maps/torch/job/corporate_jobs.dm
> +	total_positions = 0
converted it into the guard for the sol rep.

2022-02-17 02:10 UTC, Mannybrado commented
updated.

2022-02-19 00:22 UTC, Kaksisilma requested changes
There's a lot of things to fix here. I am not fond at all of the idea of the SolRep moving to the CL's office. Preferably, you'd modify the existing Vip office (which used to be the Sol Rep's) in order to accomodate both of them, else this might be confusing and hard to adapt.

At this point, I feel like just straight-up removing APA and not adding the Fed Agent, or simply keeping the APA and not giving the Sol Rep an agent might be the best idea simply for the ease of mapping. but I'll defer to @ProbablyCarl in this specific topic. 

I'm not against the addition of Sol-Rep. In fact, it has always been one of my favorite roles to play. There is simply a TON of sub-optimal stuff in this PR that seems to steer a RP role into a far more active position. I'm not sure if I mentioned this in one of the .dm reviews but there is 0 reason for the CL, APA or SolFed to have access to any other radio channel besides command (Except maybe research for CL, but even then I'd call it a bit of a stretch.)

TL;DR:
Fix the accesses.
Do not move into the CL office. Map the Vip Office back to Sol-Rep office and give them an extra locker for the SolFed agent.

My hot take is that neither of them needs a protection agent in a ship with extensive security detail, but It's an enjoyable role to play for some people so I guess it can stay.

2022-02-19 00:22 UTC, Kaksisilma commented on maps/torch/job/command_jobs.dm
> +					access_commissary,)
While I get the need to give SolRep accesses, most of those are completely out of the scope of what they should be doing. Again, they are a bureaucrat and a RP role. 

In order from most to least egregious, **no to:** access_change_ids, access_network access_aquila, access_eva, access_mailsorting, access_comissary

I'm also pretty sure access_library is a relic from bay boxstation era since it hardly appears anywhere else on code

2022-02-19 00:22 UTC, Kaksisilma commented on maps/torch/job/command_jobs.dm
> +						access_sec_guard)
Same accesses as the Sol Rep, plus sec_guard for their locker, please.

2022-02-19 00:22 UTC, Kaksisilma commented on maps/torch/job/torch_access.dm
> +
This is OK, but if you want to go for code quality, just completely replace adjudicator with rep stuff.

2022-02-19 00:22 UTC, Kaksisilma commented on maps/torch/structures/closets/misc.dm
> +		/obj/item/weapon/gun/projectile/pistol/throwback,
Are you sure this is the right pistol type?

pistol/throwback can't have their ammo printed on a lathe. I'd suggest going with some other revolver/pistol.

The obvious should be stated, so, nothing overly powerful like a hand canon.

2022-02-19 00:22 UTC, Kaksisilma commented on maps/torch/structures/closets/misc.dm
> +		/obj/item/taperoll/police
He's not part of sec. He won't need this.
```suggestion

```

2022-02-19 01:11 UTC, Mannybrado commented on maps/torch/job/command_jobs.dm
> +					access_commissary,)
understandable, done.

2022-02-19 01:12 UTC, Mannybrado commented on maps/torch/job/command_jobs.dm
> +						access_sec_guard)
done.

2022-02-19 01:12 UTC, Mannybrado commented on maps/torch/job/torch_access.dm
> +
I did this originally, but I didn't want to delete any of the adjudicator stuff just in case. I really don't want to do that in this PR, but I could in the future.

2022-02-19 01:12 UTC, Mannybrado commented on maps/torch/structures/closets/misc.dm
> +		/obj/item/weapon/gun/projectile/pistol/throwback,
I'll give them an extra mag. The federal agent having the 1911 clone is just, like... c'mon. You can always print 10mm and fill the magazines manually.
Since they are lethal rounds, and the gun is cool, them having to put a little more effort into conserving or resupplying their ammo seems like a good trade-off for me.

2022-02-19 01:12 UTC, Mannybrado commented on maps/torch/structures/closets/misc.dm
> +		/obj/item/taperoll/police
done.

2022-02-19 01:21 UTC, Mannybrado commented
> There's a lot of things to fix here. I am not fond at all of the idea of the SolRep moving to the CL's office. Preferably, you'd modify the existing Vip office (which used to be the Sol Rep's) in order to accomodate both of them, else this might be confusing and hard to adapt.

I don't see how. The CL is significantly less important to the ship(and in general), so they get the smaller office. I can see how some people might get confused for a round or two, but this is the case with literally any mapping change that effects something already in game. Its not going to cause some kind of calamity where everyone is running around like headless chickens because a single role has a different office.

Just to be clear, I moved the CL's office into the VIP room, and the SGR office into the CL's now old office. It just... makes sense that the SGR would get the better office and I prefer to focus on things that make sense when mapping.

2022-02-19 01:24 UTC, Mannybrado commented
As for the APA... I don't know. Its kind of just, like... I don't know. I would prefer to have them removed, as it makes sense to do so and its also a very shallow role, but I could understand doing some kind of vote or something.

2022-02-19 17:23 UTC, Kaksisilma commented on maps/torch/structures/closets/misc.dm
> +		/obj/item/weapon/gun/projectile/pistol/throwback,
Sure, but why would the fed agent have a shoddy pistol instead of a proper solarian pistol? By this logic we should give infantry mosins. I don't like the idea of giving the rep a throwback because it's A) fundamentally flawed from an ammo perspective even if you can load it manually, B) Why would you give a federal agent a 600 year old pistol when there are better alternatives, C) It's not only old, it's also shoddy and has four different sprites that are not necessarily a 1911. (1 in 4 chance of getting the correct one.)

2022-02-19 17:26 UTC, Kaksisilma commented
> As for the APA... I don't know. Its kind of just, like... I don't know. I would prefer to have them removed, as it makes sense to do so and its also a very shallow role, but I could understand doing some kind of vote or something.
> 
> The Fed Agent is meant to be a kind of replacement, but it serves a different general function and is meant to be more engaging for people other than the representative.

Is Fed Agent any more engaging by being assigned to the Sol Rep instead of the CL?

But I digress. Either way, I'm going to wait for @ProbablyCarl opinion on this one and we'll roll with it.

2022-02-20 18:54 UTC, Mannybrado commented on maps/torch/structures/closets/misc.dm
> +		/obj/item/weapon/gun/projectile/pistol/throwback,
sure, done.

2022-02-20 18:59 UTC, Mannybrado commented
> Is Fed Agent any more engaging by being assigned to the Sol Rep instead of the CL?

Fed Agent has more freedom to do what they like. They can do their own investigations for whatever aside from the Sol Rep, if they want. The Fed isn't a security member, but they are still a federal agent and that affords them some kind of niche gimmick. APA does nothing. They sit in the CL's office and follow them around when they leave... until someone tries to attack the CL which generally only happens every couple of rounds... then they go back to shadowing the CL. If people play Fed like that, sucks, but they at least have the power to do more than that.

2022-02-21 11:16 UTC, ProbablyCarl commented
As per Kak's review:

This PR looks good. I've a few requests if you're willing to make concessions, however.
Retain the bodyguard for CL.
Access might need touching up.


That's about it.

2022-02-22 09:31 UTC, Yawet330 commented
> > Is Fed Agent any more engaging by being assigned to the Sol Rep instead of the CL?
> 
> Fed Agent has more freedom to do what they like. They can do their own investigations for whatever aside from the Sol Rep, if they want. The Fed isn't a security member, but they are still a federal agent and that affords them some kind of niche gimmick. APA does nothing. They sit in the CL's office and follow them around when they leave... until someone tries to attack the CL which generally only happens every couple of rounds... then they go back to shadowing the CL. If people play Fed like that, sucks, but they at least have the ability to do more. You may say, "But APA can totally do interesting things!" Okay... like what? I firmly believe the only interesting gimmick as APA is rolling assistant and just... being an actually helpful assistant, yet I am literally the only person that has ever done this. I suppose being a REAL corporate goon and brutalizing people is interesting, but most CLs don't play the kind of person to allow that. Sitting around like a statue waiting for someone to attack the CL is boring and I don't understand how people can do it every round they get the role.

APA is more than just a physical guard for the Liason. They're also supposed to keep NT's; or their employers, interests at heart - beyond the liaison.

This includes cooperating with local security forces, for example, if their target goes rogue; and attempting to non-lethally subdue them/etc (unless you play a corrupt LPA); but as a better note.

The APA/LPA exists to advise and protect the CL. This extends far more than merely physically. I play LPA's that go as far as to give actual legal advice towards my target, because; simply.

You're there to
A) Ensure your employers needs are met within reason
B) Stay alive
C) Keep your target alive, and out of jail, within reason

2022-02-25 10:13 UTC, ProbablyCarl commented
No idea as to what happened to Manny.
Going to close this for now.

2022-02-25 10:13 UTC, closed without merging