GAS Job Restrictions
BoHBranch/BoH-Bay pull request #1217
Opened 2022-02-16 03:11 UTC by IvanIvanovIvanovsky

Allows all GAS to be civilians now that they are citizens under the lore. Adds Bartender and Chef to grade A, as before it was only grade B. This is my first PR in over six months so I'm keeping it simple. Playtested, looks like it works fine to me. May create another more expansive PR for reworking the shitcode that is GAS grading. I'd like feedback on what jobs you think GAS should or should not be in so feel free to comment it here incase I do make that PR.

2022-02-16 22:06 UTC, Kaksisilma commented
![Capture](https://user-images.githubusercontent.com/54181477/154365339-22df57b9-6ec5-41ec-894a-3486a729f9db.PNG)

2022-02-16 22:10 UTC, Kaksisilma requested changes
This will probably fix it.

2022-02-16 22:10 UTC, Kaksisilma commented on maps/torch/job/torch_jobs.dm
> +	/decl/cultural_info/culture/nabber/New()
```suggestion
/decl/cultural_info/culture/nabber/New()
```

2022-02-18 04:26 UTC, IvanIvanovIvanovsky commented
Once I downloaded a copy and it didn't work I edited it in DM until it did, to save time, and so I copied the changes by memory to the github version, seems like I made an error.

2022-02-18 09:37 UTC, Yawet330 commented
Good for merge if @Kaksisilma agrees

2022-02-18 14:16 UTC, benj8560 commented
wanted to suggest giving them prospecting. Always kinda made sense they would suit that kinda work. They got RIGs now and their strength makes them well suited for any labor job. I believe prospectors already get EVA so them getting their suits is already taken care of.
also no doubt some funny memes will come of having a GAS in a small enclosed space on the Gaunt *chitter

2022-02-18 18:12 UTC, Kaksisilma commented
> wanted to suggest giving them prospecting. Always kinda made sense they would suit that kinda work. They got RIGs now and their strength makes them well suited for any labor job. I believe prospectors already get EVA so them getting their suits is already taken care of. also no doubt some funny memes will come of having a GAS in a small enclosed space on the Gaunt *chitter

Sounds good on paper but on practice I think it'll be a nightmare.

Code-wise, this PR is OK so I'll go ahead and merge it. If push comes to shove we can remove passenger GAS later.

2022-02-18 18:12 UTC, merged