(Badly) ports gun attachments
BoHBranch/BoH-Bay pull request #1250
Opened 2022-02-19 01:12 UTC by Pariah919

Heavily based off the old 2018 CM code with some changes. But yeah. Here you go. Its unfinished and literally nothing uses it so far.

2022-02-20 02:12 UTC, Yawet330 commented
Incredibly based? Compiled passed? 

Merging now.

2022-02-20 15:48 UTC, Kaksisilma commented
A ton of check failures on attachments.dm

2022-02-27 23:34 UTC, Anton-Kr requested changes
Incorrect icon states.

2022-02-27 23:34 UTC, Anton-Kr commented on code/modules/projectiles/guns/attachments.dm
> +	icon_state = "grip"
All of the icon states are incorrect.

2022-02-27 23:34 UTC, Anton-Kr commented on code/modules/projectiles/guns/attachments.dm
> +	icon_state = "holosight"
This iconstate is missing.

2022-02-27 23:34 UTC, Anton-Kr commented on code/modules/projectiles/guns/attachments.dm
> +	icon_state = "holosight"
ditto

2022-02-27 23:39 UTC, Anton-Kr requested changes
Other issue -> sprites of attachments disappear on the sprite on the firearm changing (ie ammo running out, mag removed, etc)

2022-02-27 23:39 UTC, Anton-Kr commented on code/modules/projectiles/guns/projectile/automatic.dm
> +		/obj/item/attachable/verticalgrip,
Not sure if you intended for this to actually be used in game rather then the example, but if you are the offset is off and looks a biiit weird

2022-03-05 16:24 UTC, Anton-Kr commented
This ready for review @Pariah919 ?

2022-03-06 06:11 UTC, Pariah919 commented on code/modules/projectiles/guns/projectile/automatic.dm
> +		/obj/item/attachable/verticalgrip,
Sorry for being literally a week late but I've been busy the last week, but no the fullauto smg is more of an "example piece" for people to guideline themself ~~or copy paste it as an example LMAO~~ for new guns.

2022-03-08 12:50 UTC, ProbablyCarl commented
Marking as a draft until the author states this is ready for review.

2022-03-10 16:29 UTC, Anton-Kr approved these changes

2022-03-10 16:29 UTC, merged