New Vox ship!
BoHBranch/BoH-Bay pull request #1319
Opened 2022-02-25 23:33 UTC by Armyguy

Adds in a new Vox ship with things like, a hull, beds, food, windows.

2022-02-26 01:33 UTC, Armyguy commented
Well THAT was fun, what started with "Why are my ladder not working?" turned in to "ITS ALL OFF BY TWO!"

2022-02-26 20:56 UTC, Armyguy commented
Yea fuck it, if the OFD don't work I can fix it later. I have it flagged for "TEMPLATE_FLAG_SPAWN_GUARANTEED" for now to see any bugs that pop up.

2022-02-26 22:20 UTC, Rayfod commented
![Skærmbillede 2022-02-26 225617](https://user-images.githubusercontent.com/63320341/155860569-25e6f0c6-c951-4c0a-8249-e47dd355e7de.png)
![Skærmbillede 2022-02-26 225737](https://user-images.githubusercontent.com/63320341/155860576-c0e2ae74-1984-4681-8e5c-670e328cb0b1.png)
![Skærmbillede 2022-02-26 225827](https://user-images.githubusercontent.com/63320341/155860582-22fb72b1-925d-4819-b34f-fe52f15f2cda.png)
![Skærmbillede 2022-02-26 230226](https://user-images.githubusercontent.com/63320341/155860586-ce927412-4bf0-4a1f-beb9-b665b4702b9f.png)
Pipe problems
12 people are on the ship, and they all need armor, insulated gloves and jet-packs.
1 thermal?
I don't know why the 3 random laser weapons was dropped.
Normally the standard for chemical dispensers are for away ship is two, since you have no way to get more into the ship.
![Skærmbillede 2022-02-26 230429](https://user-images.githubusercontent.com/63320341/155860589-d76027ae-82ad-4c1e-ab6d-b454b2e7889a.png)
the OFD works fine on the test merge, but I don't think it's a good idea for them to spawn with ascent charges.
They are extremely overpowered for a good reason.
![Skærmbillede 2022-02-26 231200](https://user-images.githubusercontent.com/63320341/155860713-603b029c-3492-4dc6-a988-01c2fb15c69b.png)
No nanopaste for the stacks?
![Skærmbillede 2022-02-26 231339](https://user-images.githubusercontent.com/63320341/155860749-1aed491b-bec0-44d6-a95f-252ee3acc7b3.png)
Money is needed for vendors
MRE box missing?
![Skærmbillede 2022-02-26 231821](https://user-images.githubusercontent.com/63320341/155860855-12c356b9-1d15-437a-8b9b-1a2ccdb29aa2.png)
No power to the bridge
![Skærmbillede 2022-02-26 232006](https://user-images.githubusercontent.com/63320341/155860879-4b21efdf-e672-4074-9c16-d1c271560754.png)
And the nearby room

2022-02-26 22:37 UTC, Armyguy commented
The APC I fixed before you posted, and fix for finding the pipes I had a really hard time finding them.

As for the chemical dispensers. The only one has two is the skrell ship, and it has a ERT! one and a plan stock one.

2022-02-26 22:48 UTC, Armyguy commented
And I feel they don't ALL need armor, like unless they are raided, the idea of not only 12 vox joining the round. But that ALL of them want to do a away, is unlikely.

2022-02-26 23:11 UTC, Anton-Kr commented
Please remove ascent charges or kosmag charges. Im cool with a unique vox charge if you want to code a non OP one.

2022-02-26 23:25 UTC, Armyguy commented
> Please remove ascent charges or kosmag charges. Im cool with a unique vox charge if you want to code a non OP one.

I mean, I can try. But your 1st going to run by me what you mean by "non-OP".

2022-02-26 23:39 UTC, Armyguy commented
Ok added the Vox round. Its a HE/EMP with a blast just a bit bigger then the HE one but with a big EMP to back it up.

2022-02-27 23:51 UTC, Anton-Kr commented
Were the rest of the issues pointed out by rayfod resolved?

On the other hand
Thank you @Rayfod for the review. Your assistance is quite appreciated! 👍

2022-02-27 23:52 UTC, Anton-Kr commented on code/modules/overmap/disperser/disperser_charge.dm
> +/obj/structure/ship_munition/disperser_charge/vox/fire(turf/target, strength, range)
Kindly quantify how many shells in total are on the ship? Otherwise this shell appears more then ok balance wise.

2022-02-28 06:05 UTC, Armyguy commented on code/modules/overmap/disperser/disperser_charge.dm
> +/obj/structure/ship_munition/disperser_charge/vox/fire(turf/target, strength, range)
Same as the dagon, 16

2022-02-28 19:03 UTC, Anton-Kr requested changes
`/obj/machinery/porta_turret/ssv/vox`
Please make this it's own subtype that doesn't use the SSV as subtype so something akin to 
`/obj/machiner/porta_turret/vox`

2022-02-28 19:11 UTC, Anton-Kr requested changes
I am not sure how many dark matter cannons exist on current vox ship, but please remove them from the armory since you get a good amount of weapons from the kit anyway. Not worried about the other weapons.

2022-02-28 19:12 UTC, Anton-Kr requested changes
Give dart gun ammo. Don't care much about how much ammo.

2022-02-28 19:24 UTC, Anton-Kr commented on maps/away/voxship/voxship.dm
> +	cost = 0//From 0.5
I know the intent is to test it across a few rounds before moving it back to being random spawned. Please have a PR ready within 24 hrs that reverts this back to not being guaranteed. Thank you!

2022-02-28 19:43 UTC, Anton-Kr requested changes
90,77 on voxship-1.dmm is incorrectly a scrubber pipe

2022-02-28 19:44 UTC, Anton-Kr requested changes
No conveyor belt lever for the ore processor

2022-02-28 19:46 UTC, Anton-Kr requested changes
109, 78 omni gas filter not set up.

2022-02-28 19:47 UTC, Anton-Kr requested changes
117, 66 wall where airlock is.

2022-02-28 19:49 UTC, Armyguy commented
> No conveyor belt lever for the ore processor

Does not need it, the belt is just for show

2022-02-28 19:50 UTC, Anton-Kr requested changes
115, 75 leaky scrubber

2022-02-28 19:51 UTC, Armyguy commented
> 90,77 on voxship-1.dmm is incorrectly a scrubber pipe

fixed

2022-02-28 19:51 UTC, Armyguy commented
> 109, 78 omni gas filter not set up.

its like that on the vox ship we are using.

2022-02-28 19:53 UTC, Armyguy commented
> 115, 75 leaky scrubber

Was part of the busted up ship, but is fixed

2022-02-28 19:53 UTC, Armyguy commented
> 117, 66 wall where airlock is.

fixed

2022-02-28 19:54 UTC, Armyguy commented
> Give dart gun ammo. Don't care much about how much ammo.

The lathe can make ammo for it. And has all the mats to make a LOT of ammo for it

2022-02-28 19:55 UTC, Armyguy commented
> I am not sure how many dark matter cannons exist on current vox ship, but please remove them from the armory since you get a good amount of weapons from the kit anyway. Not worried about the other weapons.

Well if the kits ever get removed I am adding them back, but ok?

2022-02-28 19:56 UTC, Anton-Kr commented
>its like that on the vox ship we are using.

We're not held to previously bad standards. Look into how dagon atmos handles it, it's not that big of a change. If you can't figure it out, that's ok. 

>if kits get removed

Sure. I just don't think additional to what you get from kit is needed.

2022-02-28 19:56 UTC, Armyguy commented
> `/obj/machinery/porta_turret/ssv/vox` Please make this it's own subtype that doesn't use the SSV as subtype so something akin to `/obj/machiner/porta_turret/vox`

I am just using a some thing that's in there. It does not REALLY matter as all ssv is, is a ID mod and it having its paint job edited.

2022-02-28 19:59 UTC, Anton-Kr commented
SSV also uses a unique projectile, which I don't have an issue with the Vox ship using but this is more for the sanity of the next person who touches it. I really need it to not be a subtype of SSV. It's just stinky coding practice otherwise.

2022-02-28 20:01 UTC, Armyguy commented
> > its like that on the vox ship we are using.
> 
> We're not held to previously bad standards. Look into how dagon atmos handles it, it's not that big of a change. If you can't figure it out, that's ok.
Have you seen how the dagon does it?, It will take me a good hour to find out how to do it. As it does it all by numbers no text, so I will have to go over them all to find out what numbers means what, and then replace them on the one we have.

2022-02-28 20:53 UTC, Armyguy commented
> 

Done

2022-03-01 00:05 UTC, Anton-Kr approved these changes

2022-03-01 00:05 UTC, Anton-Kr requested changes
Resolve CI issues.

2022-03-01 01:40 UTC, Anton-Kr approved these changes

2022-03-01 01:42 UTC, Anton-Kr commented
Test merged. Please make a PR within 24 hrs of this being live on the server reverting the guaranteed spawn. This should leave ample time to observe/play a few rounds and fix any issues. 

Thank you.

2022-03-01 01:43 UTC, merged