Changes the Z-6 to be more of an Auto Rifle, and merges it with disposable launcher for CT.
BoHBranch/BoH-Bay pull request #1336
Opened 2022-02-27 05:07 UTC by Pariah919

## About The Pull Request
Z-6 rebalanced, .25 fire rate. Pen multiplier added.
Merged with Disposable.

## Why It's Good For The Game
Makes the Disposable not leave CT without a longarm ~~which sort of ruins the entire disposable part lol~~ and makes the Z6 have a nice niche.

2022-02-27 14:42 UTC, BurpleBineapple requested changes

2022-02-27 14:42 UTC, BurpleBineapple commented on maps/torch/infantry/firearms.dm
> +	name = "Z-6 Komodo Automatic Rifle"
I recommend keeping this as Z6 Komodo to fit with the other Z weapons. The LMG is called the Z2 Sheol, the rifle is called the Z9 Bulldog, so no need to add a dash and 'automatic rifle'

2022-02-27 15:06 UTC, ProbablyCarl commented
Revert the name and I'll merge this, as per Pineapple's take.

2022-02-27 22:04 UTC, Pariah919 commented on maps/torch/infantry/firearms.dm
> +	name = "Z-6 Komodo Automatic Rifle"
```suggestion
	name = "Z6 Komodo"
```

2022-02-27 23:46 UTC, Anton-Kr reviewed
Unfortunately you got caught in a different change. `penetration_mult ` has been changed to `penetration_mod `  and is now additive. 

See https://github.com/BoHBranch/BoH-Bay/pull/1334 for details.

2022-02-27 23:48 UTC, Anton-Kr commented on maps/torch/infantry/firearms.dm
> +		list(mode_name="automatic",  automatic = TRUE, fire_delay = 2,5, burst = 1, burst_delay = 0, move_delay=2, dispersion= 0),
is that `2,5` meant to have a comma?

2022-02-27 23:49 UTC, Anton-Kr requested changes
see above

2022-02-28 03:03 UTC, Anton-Kr commented on maps/torch/infantry/firearms.dm
> +		list(mode_name="automatic",  automatic = TRUE, fire_delay = 2,5, burst = 1, burst_delay = 0, move_delay=2, dispersion= 0),
also why the zero dispersion?

2022-03-01 13:01 UTC, BurpleBineapple requested changes

2022-03-01 13:01 UTC, BurpleBineapple commented on maps/torch/infantry/firearms.dm
> +	penetration_mult = 1.1
```suggestion
	penetration_mod = 3.5
```

2022-03-01 13:01 UTC, BurpleBineapple commented on maps/torch/infantry/firearms.dm
> +	penetration_mult = 1.1
This would fix the error. The armor pen of 5mmR is 35, so 10% extra would be 3.5.

2022-03-03 02:07 UTC, Pariah919 commented on maps/torch/infantry/firearms.dm
> +	penetration_mod = 5
```suggestion
	penetration_mod = 3.5
```

2022-03-04 21:18 UTC, Anton-Kr approved these changes

2022-03-05 02:57 UTC, merged