[DRAFT] Makeshift Weaponry expansion
BoHBranch/BoH-Bay pull request #1400
Opened 2022-03-02 22:36 UTC by ShadeAware

### CRETH TECH

**Introduction**
Increases the availability, ease of construction, and amount of **Makeshift Weaponry** available to crewmen.
Rather than simply random assortments of bullshit cobbled together to make one random-caliber weapon, you can now find and make _pieces_ of weaponry; combine weaponry pieces together, and you can make specific kinds of weapons, including guns and bombs!
![image](https://user-images.githubusercontent.com/57020074/156461408-9c6cd545-175a-45ca-a9a7-ea69875d260d.png)
![image](https://user-images.githubusercontent.com/57020074/156461421-a5cc9276-3a79-4521-b2df-9906545ad577.png)

**How do I craft?**
In absence of a proper crafting menu, I have tried to make the crafting process as easy as possible within the slap-craft framework; all components and steps have descriptions as to what they do and what they need. As a basic rule of thumb, the general crafting process goes something like this:
1. Find a _Gun Chassis_ and secure it with a screwdriver.
2. Find some _Gun Internals_ and install them into the chassis.
3. Install a _Gun Barrel_
4. Install a _Grip_
5. Find and install a _specification part._ Specification parts are unique bits of a gun that decide the final end product!
![image](https://user-images.githubusercontent.com/57020074/156461470-7f38e4de-b115-49a9-9d41-4112127af9f2.png)
![image](https://user-images.githubusercontent.com/57020074/156461477-6c2e4dc2-d761-4156-9e6f-6e4aa3caff2a.png)
![image](https://user-images.githubusercontent.com/57020074/156461481-d3fa4bba-9642-44c2-b28a-e75aa23ad54b.png)

### This is a HEAVY WIP and is currently unfinished. More to come and some things are subject to change.

2022-03-05 01:45 UTC, ShadeAware commented
GOOD ENOUGH

2022-03-05 01:47 UTC, Kaksisilma commented
Gonna be testing this tomorrow and if any balance-related issue comes up I'll let you know @ShadeAware
otherwise looks great.

2022-03-05 01:52 UTC, ShadeAware commented
Duly noted, the balance on this is subject to change due to some very rough numbers.

2022-03-05 02:10 UTC, ShadeAware commented
No longer good enough because shit was ### CHANGED AGAIN

2022-03-05 02:14 UTC, Kaksisilma requested changes

2022-03-05 02:14 UTC, Kaksisilma commented on code/modules/projectiles/guns/projectile/zipgun.dm
> +	has_safety = FALSE
couple of failed checks here.

2022-03-05 02:17 UTC, ShadeAware commented on code/modules/projectiles/guns/projectile/zipgun.dm
> +	has_safety = FALSE
Im well aware

2022-03-05 02:17 UTC, ShadeAware commented
that should hopefully be the end of the tomfuckery

2022-03-06 00:54 UTC, Kaksisilma approved these changes
Good to merge?

2022-03-06 02:28 UTC, merged