Vox slave implant - finale version
BoHBranch/BoH-Bay pull request #1406
Opened 2022-03-03 23:04 UTC by Rayfod

But I still cannot add shit to the vox map

Adds a vox slave implant
Added the prompt, added a lockbox for it all
Did a bunch of coding

2022-03-03 23:42 UTC, Anton-Kr requested changes

2022-03-03 23:42 UTC, Anton-Kr commented on code/modules/mob/living/simple_animal/hostile/voxslug.dm
> +	health = 50
Putting unrelated changes in a PR that doesn't mention them is bad. If you want vox slugs buffed, make a seperate PR. The faction fix is however fine.

2022-03-03 23:43 UTC, Rayfod commented on code/modules/mob/living/simple_animal/hostile/voxslug.dm
> +	health = 50
Ah sure, I asked Carl beforehand if it was okay which is why I took it in.

2022-03-03 23:47 UTC, Rayfod commented
**Please do not merge this PR in the next 24 hours**

2022-03-04 01:21 UTC, Rayfod commented
Yeah, my fork is still suffering since I did not get the map update from #1408, so I will most likely have to close this PR as well.

2022-03-04 01:32 UTC, Anton-Kr commented
Can always add it to map in separate PR, up to you.

2022-03-04 01:35 UTC, closed without merging