[DRAFT] [DNM] The Ascent Tiro, a Khaarmani - Human role for the Seedship.
BoHBranch/BoH-Bay pull request #1427
Opened 2022-03-06 01:29 UTC by ShadeAware

### Ascent Tiro
The Ascent Tiro is a new role for the Ascent Seedship designed to give players the opportunity to interact with the Khaarmani in a low-stress environment, provide greater political/ethical intrigue in the wider functioning of Sol society and its people, and ultimately provide a new spin on the Ascent while providing them new content that will facilitate more and different Dagon interactions.
![image](https://user-images.githubusercontent.com/57020074/156905256-405d0e5b-337b-43a7-ab23-1662bdcaba0a.png)

**What is the Tiro's Role?**
The Tiro acts as a kind of general assistant aboard the seedship, similar to its worker caste - though more versatile. A Human by species, the Tiro has been augmented with a unique kind of lung which allocates them to breathe in both oxygen-rich and bromine-rich atmospheres, with an accompanying suit of Ascent design which puts them about on par with their abilities.
![image](https://user-images.githubusercontent.com/57020074/156905389-e50ecc9b-51a7-40d6-9584-037db7fd8488.png)

**How would a Tiro act?**
As a Human, the Tiro's loyalty may be in question. The role has been left ambiguous enough for the individual player to decide _why_ exactly they're there; perhaps the person was sold into slavery, or betrayed by comrades. Maybe the individual has grown tired of Solar decadence and militarism and has sought a better life elsewhere. Maybe they were "saved" from a catastrophe by the passing seedship. Maybe they just want a badass suit.
![image](https://user-images.githubusercontent.com/57020074/156905400-44804b55-e6b6-44cb-ae5d-002036b08f67.png)

### This is a WIP PR and a lot of stuff is subject to change

2022-03-06 03:21 UTC, ShadeAware commented
Lil sneak peak of a sprite concept
![image](https://user-images.githubusercontent.com/57020074/156907819-7342b7e8-09d6-4fc1-b3d3-b2011f6c0cc0.png)

2022-03-06 06:52 UTC, Anton-Kr requested changes

2022-03-06 06:52 UTC, Anton-Kr commented on code/modules/ascent/ascent_rigs.dm
> +		laser = 1.2 * ARMOR_LASER_MAJOR,
Do not use multiplies in defines.

2022-03-06 06:52 UTC, Anton-Kr commented on code/modules/ascent/ascent_rigs.dm
> +		laser = 1.2 * ARMOR_LASER_MAJOR,
For consistency please use same armor as Alates

2022-03-06 06:52 UTC, Anton-Kr commented on code/modules/ascent/ascent_rigs.dm
> +/obj/item/weapon/rig/mantid/tiro
Majority of these are defined in parent mantid/ which means this will inherit armor, equipment etc if left blank. Please do that for anything that is left unchanged from the alate hardsuit.

2022-03-06 06:52 UTC, Anton-Kr commented on code/modules/clothing/under/miscellaneous.dm
> +	max_heat_protection_temperature = FIRESUIT_MAX_HEAT_PROTECTION_TEMPERATURE
This makes it have very serious fire protection which doesn't make much sense for just a fatigue suit as it wouldn't cover the rest of the body.

2022-03-06 06:52 UTC, Anton-Kr commented on maps/away/ascent/ascent_jobs.dm
> +	skill_points = 50 //Just *about* the # for a Roboticst at default, counting their preset skills. We have no min-skill level for this role since anyone could be deemed "interesting".
Veeeery iffy on the amount of points. 35 seems more reasonable.

2022-03-06 06:54 UTC, Anton-Kr commented
A bit confused on what was changed about ascent-2.dmm with the tiles placed. Could you just briefly explain?

2022-03-06 06:56 UTC, Anton-Kr commented
Map looks fine and passes CI. CI issues exist currently just with output logs, which obviously won't happen on code completion.

2022-03-06 07:00 UTC, Anton-Kr commented on maps/away/ascent/ascent_jobs.dm
> +		qdel(H)
this deletes the hooman

2022-03-06 16:16 UTC, ShadeAware commented on code/modules/clothing/under/miscellaneous.dm
> +	max_heat_protection_temperature = FIRESUIT_MAX_HEAT_PROTECTION_TEMPERATURE
This was copied over from some other jumpsuits and will be changed, thank you for pointing it out.

2022-03-06 16:16 UTC, ShadeAware commented on code/modules/ascent/ascent_rigs.dm
> +		laser = 1.2 * ARMOR_LASER_MAJOR,
Changed on local development branch, will push.

2022-03-06 16:16 UTC, ShadeAware commented on code/modules/ascent/ascent_rigs.dm
> +/obj/item/weapon/rig/mantid/tiro
Changed on local development branch, will push.

2022-03-06 16:17 UTC, ShadeAware commented on maps/away/ascent/ascent_jobs.dm
> +	skill_points = 50 //Just *about* the # for a Roboticst at default, counting their preset skills. We have no min-skill level for this role since anyone could be deemed "interesting".
50 is intended, as it is the (cumulative) number of points afforded to a station-bound **Roboticist** (used as a base). This includes the points usually taken away from them and put into required skills like complex devices, which is why its as high as it is; theres no minimum skill requirement thats taking points away.

2022-03-06 16:18 UTC, ShadeAware commented on maps/away/ascent/ascent_jobs.dm
> +		qdel(H)
This entire function is super fucked and I need a lot of help with it.

2022-03-06 16:18 UTC, ShadeAware commented
> 
Layering of tiles to prevent no-roof on the bottom layer, which would vent atmosphere.

2022-03-06 16:19 UTC, ShadeAware commented
> A bit confused on what was changed about ascent-2.dmm with the tiles placed. Could you just briefly explain?

Layering of tiles to prevent no-roofing and prevent atmos venting.

2022-03-07 01:05 UTC, Anton-Kr commented on maps/away/ascent/ascent_jobs.dm
> +	skill_points = 50 //Just *about* the # for a Roboticst at default, counting their preset skills. We have no min-skill level for this role since anyone could be deemed "interesting".
Still no thanks on 50. I'll settle on 40.

2022-03-07 03:55 UTC, Anton-Kr commented on maps/away/ascent/ascent_jobs.dm
> +	skill_points = 50 //Just *about* the # for a Roboticst at default, counting their preset skills. We have no min-skill level for this role since anyone could be deemed "interesting".
Fiiiine. 50 is cool

2022-03-07 07:32 UTC, Shirumic commented
Ascent lore maintainer here, current ideas on how to integrate Tiros with the lore:
Not all gynes would have them of course, I'm thinking a tiro could be any species that's compatible for augmentation
but seeing that ascent are really big on espionage, enterprising gynes would of course try to have some humans around to help keep an eye on the rapidly developing human empire
maybe one of their implants enforces their loyalty to their patron-gyne since they wouldn't have complete ascent citizenship
yeah that could be it
since they're not ascent citizens gynes can get away with psychologically conditioning tiros for absolute loyalty
and then they're used as a gyne's foreign agents, akin to the real germanic guard

(though alates are by far more loyal than anything else everyone in the ascent plays politics, tiros could be a way for certain gynes to bypass that risk of betrayal)

We'll see what else needs to be written, keep me up to date! I'm really excited about this.

2022-03-09 23:08 UTC, Anton-Kr commented
Having had a better look at the map, their quarters are too disproportionate to what I think their role should be as a bottom of the barrel human aboard an Ascent vessel. It needs to be narrowed to a size of a broom closet. Currently it's a bit too big and unreasonable.

2022-03-09 23:21 UTC, Anton-Kr commented
Following further thoughts, I am against the idea of "Pars" existing. Equipment wise, I don't see a need for change, however this role does not require a second special snowflake sub-role, and a human serving as a bodyguard to the Gyne outright makes zero sense to me. The idea that some pair of players will by default grant this "rank" while excluding others who may wish to play the role will promote metaganging to an extent where it becomes a code, rather than a lore issue. 

Overall -- Tiro existing as bottom of the barrel below even Alate's scum fine. Anything that puts them on "Par" (yes the verbiage is intended) will not be merged. Items wise, I am fine with them having armor and weapons, however I want both to be locked behind the Gyne (this includes the human support armor equivalent). 

This comment/change request has been seconded by head administrator Incelestine as well as a fellow maintainer @N8-Toe. I understand that this news may be disappointing, however this job even with the changes I listed has potential to be a clusterfuck of metabuddying, meta-gaming issues, and you made it expressively clear that you were making this job for yourself in mind, thus casting a balancing hand here is important.

2022-03-09 23:24 UTC, Anton-Kr requested changes

2022-03-09 23:24 UTC, Anton-Kr commented on code/modules/ascent/ascent_rigs.dm
> +/obj/item/rig_module/chem_dispenser/nabber/tiro
I am assuming this subtype uses chems that humans and GAS use? In that case please rename the nabber chem dispenser to something like "carbon-lifeforms" chem dispenser and have both use the same type.

2022-03-09 23:24 UTC, Anton-Kr commented on code/modules/ascent/ascent_rigs.dm
> +	allowed = list(
Why isn't this inherited from mantid suit?

2022-03-09 23:24 UTC, Anton-Kr commented on maps/away/ascent/ascent_jobs.dm
> +	info = "You are an Ascent Tiro, servant to the independent Ascent vessel. How you ended up in this position is known only to you and the Khaarmani. Assist the Gyne and Queen in their duties - or, fi
```suggestion
	info = "You are an Ascent Tiro, servant to the independent Ascent vessel. How you ended up in this position is known only to you and the Khaarmani, however you are at the bottom of the hierarchy aboard the ship, below that of even the Alates. Assist the vessel to earn the Gyne's trust or find means to escape."
```

2022-03-09 23:24 UTC, Anton-Kr commented on maps/away/ascent/ascent_jobs.dm
> +	info = "You are an Ascent Tiro, servant to the independent Ascent vessel. How you ended up in this position is known only to you and the Khaarmani. Assist the Gyne and Queen in their duties - or, fi
Feel free to reword it, but make it explicitly clear that they are below the Alates.

2022-03-09 23:24 UTC, ShadeAware commented
> Following further thoughts, I am against the idea of "Pars" existing. Equipment wise, I don't see a need for change, however this role does not require a second special snowflake sub-role, and a human serving as a bodyguard to the Gyne outright makes zero sense to me. The idea that some pair of players will by default grant this "rank" while excluding others who may wish to play the role will promote metaganging to an extent where it becomes a code, rather than a lore issue.
> 
> Overall -- Tiro existing as bottom of the barrel below even Alate's scum fine. Anything that puts them on "Par" (yes the verbiage is intended) will not be merged. Items wise, I am fine with them having armor and weapons, however I want both to be locked behind the Gyne (this includes the human support armor equivalent).
> 
> This comment/change request has been seconded by head administrator Incelestine as well as a fellow maintainer @N8-Toe. I understand that this news may be disappointing, however this job even with the changes I listed has potential to be a clusterfuck of metabuddying, meta-gaming issues, and you made it expressively clear that you were making this job for yourself in mind, thus casting a balancing hand here is important.

Im deferring to Carl regarding the Par due to your propensity to flip-flop on the issue and the immense amount of effort and work put into the content surrounding both the Tiro and the Par. Make up your mind beforehand next time.

2022-03-09 23:25 UTC, ShadeAware commented on maps/away/ascent/ascent_jobs.dm
> +	info = "You are an Ascent Tiro, servant to the independent Ascent vessel. How you ended up in this position is known only to you and the Khaarmani. Assist the Gyne and Queen in their duties - or, fi
No.

2022-03-09 23:26 UTC, ShadeAware commented on code/modules/ascent/ascent_rigs.dm
> +	allowed = list(
Small changes to the list.

2022-03-09 23:48 UTC, Anton-Kr requested changes
Resolve issues shown in comment.

2022-03-10 03:49 UTC, Anton-Kr commented on maps/away/ascent/ascent_jobs.dm
> +	H.verbs |= /mob/living/carbon/human/proc/identity_rename
Not really seeing the need for this as it's not like you are joining this with an onship role.

2022-03-10 04:16 UTC, ProbablyCarl commented
Given the work has been done, I'd say we leave it as is and go ahead with a merge. We'll work out the issues after it has been implemented. No need to kill something before it has had a chance to prove itself potentially problematic.

2022-03-11 01:22 UTC, ShadeAware commented on maps/away/ascent/ascent_jobs.dm
> +	H.verbs |= /mob/living/carbon/human/proc/identity_rename
It uses onship characters

2022-03-11 08:40 UTC, ProbablyCarl commented
Catwalks are stacked. Take a look.
100-90-10

2022-03-12 06:00 UTC, merged