Removes infantry access to the polyp
BoHBranch/BoH-Bay pull request #1430
Opened 2022-03-06 17:34 UTC by N8-Toe

At request of HIghAdmiral. Removes infantry access to the polyp

Changelog included

2022-03-06 19:37 UTC, Anton-Kr commented
Changelog is messing up CI. Feel free to outright remove it

2022-03-06 20:09 UTC, Anton-Kr requested changes

2022-03-06 20:09 UTC, Anton-Kr commented on html/changelogs/N8Toe-Infpolypaccess.yml
> +################################
remov

2022-03-06 21:00 UTC, N8-Toe commented on html/changelogs/N8Toe-Infpolypaccess.yml
> +################################
done. death to the changelogs

2022-03-07 01:37 UTC, Anton-Kr approved these changes

2022-03-07 02:51 UTC, merged