Deck Officer alt title + Fleet Prospector
BoHBranch/BoH-Bay pull request #1438
Opened 2022-03-07 16:38 UTC by Jul-Jul

Just as the title says, I've added the Quartermaster alt title for Deck Officer, and also made it so Fleet characters can now play Prospector considering this to be a military vessel, there would be military personnel also trained to fill such role.

2022-03-07 17:49 UTC, Anton-Kr approved these changes

2022-03-07 17:49 UTC, Anton-Kr commented on maps/torch/job/supply_jobs.dm
> +								/datum/mil_rank/fleet/e5,
No reason for it to be that high and I am on rank reduction campaign. E2-E5 please.

2022-03-07 17:50 UTC, Anton-Kr requested changes

2022-03-07 17:50 UTC, Anton-Kr commented on maps/torch/job/supply_jobs.dm
> +								/datum/mil_rank/fleet/e5,
Make this E2-E5. Too high of a rank imo.

2022-03-07 17:50 UTC, Anton-Kr commented on maps/torch/job/supply_jobs.dm
> +		"Quartermaster")
I am kind of leaning towards no on this since no other leadership job has an alt title due to it honestly usually being confusing.

2022-03-07 17:58 UTC, Jul-Jul commented on maps/torch/job/supply_jobs.dm
> +								/datum/mil_rank/fleet/e5,
The reason why it's somewhat high rank is shoew that the individual is trusted specialised person who is trusted to conduct these away missions on their own.

2022-03-07 17:59 UTC, Jul-Jul commented on maps/torch/job/supply_jobs.dm
> +		"Quartermaster")
I would agree if there were Command, but Deck officer ain't even classed as Command or even Command Support.

2022-03-07 18:01 UTC, Anton-Kr commented on maps/torch/job/supply_jobs.dm
> +								/datum/mil_rank/fleet/e5,
I mean that's fair, but still leaning towards something lower. How does E-3 thru E-6 sound?

2022-03-07 18:02 UTC, Anton-Kr commented on maps/torch/job/supply_jobs.dm
> +		"Quartermaster")
I'll think about this one some more.

2022-03-07 18:07 UTC, Jul-Jul commented on maps/torch/job/supply_jobs.dm
> +								/datum/mil_rank/fleet/e5,
That's agreeable.

2022-03-07 18:11 UTC, Jul-Jul commented on maps/torch/job/supply_jobs.dm
> +		"Quartermaster")
Honestly I was considering PR putting Deck Officer under Command Support, but even then there is multiple Command Support roles who have alt titles.

2022-03-07 21:54 UTC, Anton-Kr commented on maps/torch/job/supply_jobs.dm
> +		"Quartermaster")
Eh, honestly I still would rather stick to Deck Officer just for consistency sake. Apologies!

2022-03-07 23:11 UTC, Jul-Jul commented on maps/torch/job/supply_jobs.dm
> +		"Quartermaster")
Considering I'm about to make a edit to include SNCO ranks like the old Deck officer had, I would have to include alt title Deck Chief too.

2022-03-07 23:43 UTC, Anton-Kr commented on maps/torch/job/supply_jobs.dm
> +		"Quartermaster")
Deck Chief is fine. Just don't really like QM honestly.

2022-03-08 00:18 UTC, Jul-Jul commented on maps/torch/job/supply_jobs.dm
> +		"Quartermaster")
Even though QM makes sense from a military standpoint and considering their actual role.

2022-03-08 00:21 UTC, Anton-Kr commented on maps/torch/job/supply_jobs.dm
> +		"Quartermaster")
I am fine with one or the other but not both because it's a leadership position.

2022-03-08 01:52 UTC, Anton-Kr requested changes
Incorrect indentations per CI

2022-03-08 09:32 UTC, Jul-Jul commented
Fixed issue. Deck Chief has been added as a alt title to go alongside the the SNCO ranks.

2022-03-08 18:20 UTC, Anton-Kr approved these changes

2022-03-08 18:20 UTC, merged