Supply/Munition update!
BoHBranch/BoH-Bay pull request #1475
Opened 2022-03-10 23:42 UTC by Jul-Jul

Description: This PR gives Supply (Deck Technician, Deck Officer) access to the newly added missile systems of the Dagon. The ordering, making, loading, and firing of the missiles in the case of ship to ship combat now falls to Supply. Deck Officer, and Deck Technician have also been given a few brand new alt titles to show this change, however it also includes the removal of Civilian Deck technicians...considering civilians wouldn't surely be manning a military vessel's missile weaponry.

To also nip this in the bud now before it comes up or is made a problem on the server. The Deck Officer is now in command of the missile systems, not the Bridge Officer/Tactical Officer. However, if a Deck Officer is not present, but Deck Technicians are (or aren't), the Bridge Officer/Tactical Officer has the right to command the missile systems. The Bridge Officer/Tactical Officer however remains their command over the OFD as normal. 

Possible future changes: Within the future with further feedback, and more discussion with the devs, the Supply Department may also be given a different name to show off this change of responsibilities and duties. Other changes may be that Deck Technicians and Gunnery Technicians might also be made their own separate roles instead of simply the same role with alt titles.  

If you have feedback, wanna complain at me, or suggest other things to add to Supply then message or @ me on discord. ✦ Ali'nar ✦#0001

2022-03-11 00:29 UTC, Jul-Jul commented
Not quite sure why the tests are chimping. If someone can figure out then please say.

2022-03-11 00:55 UTC, Cupax3 commented on maps/torch/job/supply_jobs.dm
> +	department_flag = SPT
```suggestion
	department_flag = SPT|SUP
```
Will put them in Command Support and Supply. Probably. So it does not break with convention of having a head in its own department.

2022-03-11 02:45 UTC, Kaksisilma requested changes, later dismissed
Looks mostly OK. A few issues I would like the opinion of @Anton-Kr on:
- Supply should not OPERATE the weapons. This duty falls to Bridge Officers. Supply should instead be charged with re-arming them.
- The Gunnery Technician alt title would be better as Munitions Technician, but admittedly this is more of a personal nitpick.
- Keep Civillian Deck Techs if possible. It is entirely feasible that reloading and resupplying weapon systems would be one of their duties.

2022-03-11 03:24 UTC, Anton-Kr commented
Concur on all above points.

2022-03-11 03:37 UTC, Jul-Jul commented
Let me just go through your points.

1. If Supply Crew (which to be soon made into a different department) were not meant to man/operate the missile systems, then what's the point making them do everything else? Secondly, it's already confirmed by Carl and other developers that 2 new roles (3 slots) to be made solely for the operation of the missiles within the near future. All I've done is simply added a placeholder until that is implemented.

2. I prefer that title too honestly.

3. If it was contractor or some kind of PMC contractor, I would agree but it was just civilian which doesn't entirely make much sense.

2022-03-11 08:33 UTC, ProbablyCarl commented
As per previous discussion on Discord:
![image](https://user-images.githubusercontent.com/25065997/157831317-c3fe0902-b5e9-4cb3-ad88-2aaa9e2bf7cd.png)

Having something unrelated to that is absolutely fine, as it was just the product of a five second conversation.
I'll look over this shortly.

2022-03-12 21:18 UTC, N8-Toe commented
i think a dedicated munitions team would be best. but I can work on that myself in the near future. I just eeehhhh on the idea of non military crew working the weapons

2022-03-14 23:37 UTC, Anton-Kr requested changes
Due to lack of of attention to this I'll request the following
- Return of civilians to supply
- Change in description to be something along the lines of. "For military members of the department, the job also includes handling and assembling missiles, and prepping OFD charges as required by command." 

I am fine with civilians having access to the job, and I think it being IC enforceable is reasonable. This allows civie cargo techs to continue to just exist as civie cargo techs. On completion of these changes I will merge the PR.

2022-03-16 01:09 UTC, Anton-Kr approved these changes

2022-03-16 01:10 UTC, merged