Uniform Update
BoHBranch/BoH-Bay pull request #1484
Opened 2022-03-11 04:08 UTC by AMcilraith

Changes from NTEF Loadout to Fleet Loadout

2022-03-11 04:10 UTC, Anton-Kr requested changes

2022-03-11 04:10 UTC, Anton-Kr commented on maps/torch/datums/uniforms_fleet.dm
> +	name = "NTEF science"
NTEF name

2022-03-11 04:13 UTC, AMcilraith commented on maps/torch/datums/uniforms_fleet.dm
> +	name = "NTEF science"
This is the default listing, just copied it from the normal use file, and put it here

Dunno what to say tbh

2022-03-11 19:43 UTC, AMcilraith commented on maps/torch/datums/uniforms_fleet.dm
> +	name = "NTEF science"
Fixed

2022-03-11 19:47 UTC, ProbablyCarl commented on maps/torch/datums/uniforms.dm
> -/*
What's up with uncommenting this?
It's defined elsewhere, in [maps/torch/datums/uniforms_fleet.dm](https://github.com/BoHBranch/BoH-Bay/pull/1484/files#diff-f910937b45d1b5e84d4f5c4fa4b2cb54d2850278f0b387b4ea7818f7b66821b4), and this was commented out for a very good reason.

2022-03-11 19:48 UTC, AMcilraith commented on maps/torch/datums/uniforms.dm
> -/*
Okay, so it's uncommented due to being necessary for the uniform changes. Essentially, this allows me to fix it by re-adding the default fleet uniforms

2022-03-11 19:49 UTC, AMcilraith commented on maps/torch/datums/uniforms.dm
> -/*
Don't worry, cloaks are not gone, just the NTEF uniforms

2022-03-11 21:11 UTC, N8-Toe commented
I'm not a fan of the service uniforms with a stripe, I think its un-needed visual noise that lowers the quality of the sprite. 

Otherwise I do appreciate the switchover from the old EC uniforms to fleet in the vendor!

2022-03-12 20:14 UTC, AMcilraith commented
Had to rebase due to new updates

2022-03-12 20:14 UTC, closed without merging