Serpentid queen, the medical support
BoHBranch/BoH-Bay pull request #1494
Opened 2022-03-11 20:42 UTC by Rayfod

The Serpentid queen was using their entire point catalog of various medical-related skills
![Skærmbillede 2022-03-11 213834](https://user-images.githubusercontent.com/63320341/157959542-869cb812-5fb6-44c0-b5b1-451cf990d84f.png)

2022-03-12 02:32 UTC, Cupax3 commented on maps/away/ascent/ascent_jobs.dm
> +					SKILL_CHEMISTRY   = SKILL_ADEPT)
Pedantic, but if you align one set of skills, why not align the rest too?

2022-03-12 03:05 UTC, Rayfod commented
My mistake

2022-03-12 15:14 UTC, Cupax3 submitted a review, later dismissed
Code looks fine, lore/balance remains to be seen

2022-03-12 15:16 UTC, Rayfod commented
My main reason for having it added, was because of their flavor text saying "You are a Monarch Serpentid Queen living on an independant Ascent vessel. Assist the Gyne in her duties and _tend to your Workers_."

2022-03-13 18:21 UTC, Anton-Kr commented
Nothing here lowers the queens overall points

2022-03-13 18:21 UTC, Anton-Kr requested changes
Lower overall points

2022-03-13 18:31 UTC, Rayfod commented
```
SKILL_COMBAT = SKILL_BASIC,
SKILL_WEAPONS = SKILL_BASIC,
```
Their skills for combat was reduced to this, which makes their overall points 8 less
Do they need to be further reduced as well?

2022-03-13 20:13 UTC, Anton-Kr commented
Correct me if my math is wrong: 

Combat going from trained to basic is a loss of 4 points.
WE going from trained to basic is a loss of further 4 points.

Medical going from basic to experienced is 12 points
Anatomy going from nada to experienced is 16 points.

Leading to a total gain of a whopping 20 points. I am not against the Queen gaining some skill points but this is far too many.

2022-03-13 20:15 UTC, Anton-Kr commented on maps/away/ascent/ascent_jobs.dm
>  	outfit_type = /decl/hierarchy/outfit/job/monarch
```suggestion
	outfit_type = /decl/hierarchy/outfit/job/monarch
	skill_points = 14
```

2022-03-13 20:15 UTC, Anton-Kr commented on maps/away/ascent/ascent_jobs.dm
>  	outfit_type = /decl/hierarchy/outfit/job/monarch
Mind you, I am fine with them getting _some_ amount of extra points, but this PR gives them 20 which is excessive.

2022-03-13 22:29 UTC, Rayfod commented
Changes added as @Anton-Kr asked for

2022-03-15 02:24 UTC, Anton-Kr approved these changes

2022-03-15 02:25 UTC, merged