Hestia: Up-Armored Edition.
BoHBranch/BoH-Bay pull request #1547
Opened 2022-03-16 11:20 UTC by Dark1Star3s

The Great Leader is Dead.

## Fixed Mech Armor & Buffs Mechs Overall

## Thanks to help from my good friend Deceptor on discord for figuring out the armor issue.

## Changelog

- Mech Armor Fixed and now applies.
- Mech Armor Buffed across the board, all armor is stronger and more resilient.
- Mech Health buffed a lot. Minimum health on the lightest mechs from 70 to 300. The Highest at 500.

2022-03-16 13:51 UTC, githubuser4141 commented
Cool, but.. why are the /light/ parts multiple times tougher compared to power loader parts? And, why is the combat armour which requires diamond and RnD less protective then the standard armour in melee?

And.. you do realise EM armour is supposed to be less protective against standard ammunition because it makes the mech 100% immune to EMPs, right? It might not be 100% realistic for a heavily armoured vehicle to be vulnerable to pistol rounds but /realistically/ there's a heap of issues with armoured vehicles that can't/won't be simulated here so having a trade-off between ballistic/melee/laser resistance and EMP-proofness is probably good.

2022-03-16 21:40 UTC, Dark1Star3s commented
> Cool, but.. WTF's with the limb balance? Light components shouldn't be as protective as combat ones, and they shouldn't be multiple times tougher then power-loader components surely. The flavour desc. suggests Light parts are performance-oriented, so think of a sports car vs. a utility truck (power-loader) vs. a up-armored HMMWV (combat parts) vs. a... I'm not a tank buff, but let's say a Stryker-like armored vehicle (heavy parts).

Power Loaders are open to space, their entire chassis is open to the elements- while they are weaker, they hit harder than the light mech. On top of that I will be adding more material costs to these parts later, I would like to see how these handle in actual combat first. To add to your second point, EM armor is shielded against EM, it is just "Resistant" which is pretty low in armor ratings for Hestia, depending which chassis it's mounted to, you probably could kill it with just 1 or 2 mags from a bulldog.

Research is also a factor, and Robotics will require research to do their thing- and, command shouldn't be authorising battlemechs to be built- think of it like the armory. Security are not allowed their giga-chad guns until red alert. If Command starts letting Robotics build battlemechs and they start going around wrecking the place that is on them. But it's also secs job to alert command. All in all I am testing the armor buffs first, I want to see what people think of them for a while, this also fixes mech armor not working in the first place.

Purple and I spoke heavily on the balance of these and I believe it's at a good point to begin testing.

2022-03-17 03:15 UTC, githubuser4141 commented
> > Cool, but.. WTF's with the limb balance? Light components shouldn't be as protective as combat ones, and they shouldn't be multiple times tougher then power-loader components surely. The flavour desc. suggests Light parts are performance-oriented, so think of a sports car vs. a utility truck (power-loader) vs. a up-armored HMMWV (combat parts) vs. a... I'm not a tank buff, but let's say a Stryker-like armored vehicle (heavy parts).
> 
> Power Loaders are open to space, their entire chassis is open to the elements- while they are weaker, they hit harder than the light mech. On top of that I will be adding more material costs to these parts later, I would like to see how these handle in actual combat first. To add to your second point, EM armor is shielded against EM, it is just "Resistant" which is pretty low in armor ratings for Hestia, depending which chassis it's mounted to, you probably could kill it with just 1 or 2 mags from a bulldog.
> 
> Research is also a factor, and Robotics will require research to do their thing- and, command shouldn't be authorising battlemechs to be built- think of it like the armory. Security are not allowed their giga-chad guns until red alert. If Command starts letting Robotics build battlemechs and they start going around wrecking the place that is on them. But it's also secs job to alert command. All in all I am testing the armor buffs first, I want to see what people think of them for a while, this also fixes mech armor not working in the first place.
> 
> Purple and I spoke heavily on the balance of these and I believe it's at a good point to begin testing.

Your changes don't reflect PL arms hitting harder, so my bad. I think however while the chassis is 'open' lore-wise it's still supposed to a tough steel cage vs. the light chassis which is a sealed plastic and glass can, obviously the pilots are going take the brunt of the hits to PL chests, but the parts themselves are supposed to be tougher.

As for research/combat mechs, roboticists can finish research in about 30 to 40 minutes if they chose, and.. this isn't exactly TG where mechs are non-modular. Mech armor isn't visible, and you gave basic non-combat armor combat stats, so you could say an Odysseus is now a combat mech durability-wise. Also, 'heavy' parts which are absolutely useful in combat scenarios aren't actually named as such, so someone could build a "mining mech" with heavy parts, combat armor and who's going to stop them if they don't add actual guns? Plasma cutters which are a "utility" tool could be added then you'd have a 1200 HP validhunting suit that's almost invulnerable to anything that's not an EMP. In a localhost server, laser rifles did about 3 damage to the heavy armor. You're basically screwed unless you have an ion rifle.

2022-03-17 03:35 UTC, Dark1Star3s commented
> > > Cool, but.. WTF's with the limb balance? Light components shouldn't be as protective as combat ones, and they shouldn't be multiple times tougher then power-loader components surely. The flavour desc. suggests Light parts are performance-oriented, so think of a sports car vs. a utility truck (power-loader) vs. a up-armored HMMWV (combat parts) vs. a... I'm not a tank buff, but let's say a Stryker-like armored vehicle (heavy parts).
> > 
> > 
> > Power Loaders are open to space, their entire chassis is open to the elements- while they are weaker, they hit harder than the light mech. On top of that I will be adding more material costs to these parts later, I would like to see how these handle in actual combat first. To add to your second point, EM armor is shielded against EM, it is just "Resistant" which is pretty low in armor ratings for Hestia, depending which chassis it's mounted to, you probably could kill it with just 1 or 2 mags from a bulldog.
> > Research is also a factor, and Robotics will require research to do their thing- and, command shouldn't be authorising battlemechs to be built- think of it like the armory. Security are not allowed their giga-chad guns until red alert. If Command starts letting Robotics build battlemechs and they start going around wrecking the place that is on them. But it's also secs job to alert command. All in all I am testing the armor buffs first, I want to see what people think of them for a while, this also fixes mech armor not working in the first place.
> > Purple and I spoke heavily on the balance of these and I believe it's at a good point to begin testing.
> 
> Your changes don't reflect PL arms hitting harder, so my bad. I think however while the chassis is 'open' lore-wise it's still supposed to a tough steel cage vs. the light chassis which is a sealed plastic and glass can, obviously the pilots are going take the brunt of the hits to PL chests, but the parts themselves are supposed to be tougher.
> 
> As for research/combat mechs, roboticists can finish research in about 30 to 40 minutes if they chose, and.. this isn't exactly TG where mechs are non-modular. Mech armor isn't visible, and you gave basic non-combat armor combat stats, so you could say an Odysseus is now a combat mech durability-wise. Also, 'heavy' parts which are absolutely useful in combat scenarios aren't actually named as such, so someone could build a "mining mech" with heavy parts, combat armor and who's going to stop them if they don't add actual guns? Plasma cutters which are a "utility" tool could be added then you'd have a 1200 HP validhunting suit that's almost invulnerable to anything that's not an EMP. In a localhost server, laser rifles did about 3 damage to a mech w/ heavy armor, and basic mechs are effectively immune to melee. Unless the pilot is AFK, you effectively cannot fight them without an ion weapon.

I get your points, though you shouldn't be fighting a mech 1v1. It's like fighting a tank while you're a single soldier in the open. Dagon has 2 Ion Rifles and 2 Ion Pistols. Each one in the other armory. So if Ions become an issue that's securities fault. But I can see your points. I'll have to talk to purple later to see how we can make it to where combat armor is visible on the mech.

2022-03-17 03:36 UTC, Dark1Star3s commented
To add to that, once the main body is destroyed, (about 300 in the lightest body) armor is no longer effective and weapons do full damage again.

2022-03-17 04:31 UTC, Anton-Kr commented
5 incorrect indentations (expecting exactly 0)

2022-03-17 04:31 UTC, Anton-Kr requested changes
fix CI

2022-03-17 04:38 UTC, Dark1Star3s commented
I have no idea indentations are. :(

2022-03-17 04:39 UTC, Anton-Kr requested changes

2022-03-17 04:39 UTC, Anton-Kr commented on code/modules/mechs/mech_damage.dm
> +    . = ..()
this should be tabs

2022-03-17 04:45 UTC, Dark1Star3s commented
Okay. I think that did it.

2022-03-17 05:25 UTC, Dark1Star3s commented
Not entirely sure why the map checks are failing. It doesn't change anything...

2022-03-18 17:36 UTC, Anton-Kr commented
Map checks shouldn't be related to your code, just CI randomly fucking up. I'll try to get to this tmrw or in a few days. Ping me if I don't.

2022-03-20 03:34 UTC, merged