Gantry Part II
BoHBranch/BoH-Bay pull request #1550
Opened 2022-03-16 17:28 UTC by sgtmind

Adds in the gantry from BayStation12. Now with possible fixes

## About The Pull Request
New Human Provocateurs have been added. Three Vessels, and their corresponding Holopads and Ship Names might be seen.
## Why It's Good For The Game
Adds more variety to offsite roles, plus it adds a challenge
## Did You Test It?
I tested it and it seemed to work. 
## Authorship
Based from here: https://github.com/Baystation12/Baystation12/pull/29023
## Changelog

:cl:
/:cl:

2022-03-17 04:32 UTC, Anton-Kr commented
Add this to away_sites_testing so that CI can run through it.

2022-03-17 04:32 UTC, Anton-Kr requested changes
Add CI to map.

2022-03-17 13:25 UTC, sgtmind commented
How do I do that?

2022-03-17 17:12 UTC, sgtmind commented
> Add CI to map.

Think I got that fixed

2022-03-17 17:32 UTC, Anton-Kr commented
Add away site to maps/torch/torch.dm

2022-03-18 17:38 UTC, Anton-Kr commented on maps/away/scavver/scavver_gantry.dm
> +   area_usage_test_exempted_root_areas = list(/area/scavver)
Still using spaces here. Using github to edit your PRs tend to cause this issue.

2022-03-18 20:41 UTC, sgtmind commented on maps/away/scavver/scavver_gantry.dm
> +   area_usage_test_exempted_root_areas = list(/area/scavver)
I used the standard DM

2022-03-19 15:32 UTC, sgtmind commented
Anything else?

2022-03-19 20:38 UTC, Anton-Kr requested changes

2022-03-19 20:38 UTC, Anton-Kr commented on maps/away/scavver/scavver_gantry.dm
> +        /area/scavver = NO_SCRUBBER|NO_VENT|NO_APC
bad indent

2022-03-19 20:38 UTC, Anton-Kr commented on maps/away/scavver/scavver_gantry.dm
> +    )
bad indent

2022-03-19 20:38 UTC, Anton-Kr commented on maps/away/scavver/scavver_gantry.dm
> +  ..()
bad indent

2022-03-19 20:38 UTC, Anton-Kr commented on maps/away/scavver/scavver_gantry.dm
> +  software.installed_software = list(MECH_SOFTWARE_UTILITY, MECH_SOFTWARE_ENGINEERING)
bad indent

2022-03-21 16:23 UTC, Anton-Kr requested changes
Further there are a few pipes that have the wrong directions.

2022-03-21 16:23 UTC, Anton-Kr commented on maps/away/scavver/scavver_gantry.dm
> +	apc_test_exempt_areas = list(
This should only include areas that actually do not have these things. For instance if area/scavver/foo has no APC, it should be shown as such /area/scavver/foo = NO_APC. This is causing CI failures.

2022-03-21 19:32 UTC, closed without merging