Infantry hardsuit rebalance
BoHBranch/BoH-Bay pull request #1555
Opened 2022-03-16 22:01 UTC by BladeburstNINJA

## About The Pull Request
Lowers Infantry Ballistic armor by 10 and raises Infantry Laser armor by 10.
## Why It's Good For The Game
Makes it so that Infantry laser armor is more adequate, considering the number of laser wielding enemies Infantry deals with, also lowers ballistic protection so that ballistic equipped crew can more easily deal with an antag equipped with Infantry armor.
## Did You Test It?
No.
## Authorship
BladeburstNINJA
## Changelog

:cl: Lowers ballistic armor of Infantry hardsuit by 10, Raises laser armor of Infantry hardsuit by 10.
/:cl:

2022-03-17 10:51 UTC, BurpleBineapple commented on maps/torch/infantry/hardsuit.dm
> +		bullet = ARMOR_BALLISTIC_GREAT,
I'm not super on board with making a special define just for infantry armor. If you want to set it to 70, do this instead

```suggestion
		bullet = (ARMOR_BALLISTIC_RESISTANT + 5),
```

2022-03-17 10:54 UTC, BurpleBineapple requested changes

2022-03-17 10:54 UTC, BurpleBineapple commented on maps/torch/infantry/hardsuit.dm
> +		bullet = ARMOR_BALLISTIC_GREAT,
Or just set it to 70

2022-03-17 10:54 UTC, BurpleBineapple commented on maps/torch/infantry/hardsuit.dm
>  	armor = list( //Same as the old infantry hardsuits
```suggestion
	armor = list(
```
Also remove this comment since it is no longer true

2022-03-17 10:54 UTC, BurpleBineapple commented on code/__defines/armor.dm
> +#define  ARMOR_BALLISTIC_GREAT		70
```suggestion
```

2022-03-17 10:54 UTC, BurpleBineapple commented on code/__defines/armor.dm
> +#define  ARMOR_BALLISTIC_GREAT		70
Bad way of doing this, since we don't need to create an entire define for one armor value.

2022-03-17 10:55 UTC, BurpleBineapple commented
Other than though, concept looks okay. I'm not a balance lad so my thoughts aren't too weighty.

2022-03-17 18:34 UTC, BladeburstNINJA commented
Alright, give me a sec to fix it.

2022-03-18 17:01 UTC, Kaksisilma commented
Looks OK code-wise. I will defer to other maintainers in regards to the balance changes.

2022-03-19 03:13 UTC, merged