Crossfire/Xenophage doubling requirements
BoHBranch/BoH-Bay pull request #1635
Opened 2022-03-22 14:01 UTC by gilvian

## About The Pull Request

Doubles the amount needed for Benos/Crossfire since its usually leaving with 3 people shipside while crossfire is just TDM and benos is boring

## Why It's Good For The Game

makes two annoying gamemodes a bit better to play

## Did You Test It?

yes

## Authorship

Myself

## Changelog

:cl: Gilvian

* Tweak - Benos and Crossfire require more people to play
/:cl:

2022-03-22 14:17 UTC, Dark1Star3s commented
+1 and agreed.

2022-03-22 17:37 UTC, Anton-Kr commented
It should be noted that this requires 32 players to be READIED at round start for the gamemode to occur. Even on high pop that... doesn't really happen that often from my recent memory. Code wise looks good, but this will make either very unlikely to happen. I'd drop it down to maybe I dunno, 18?

2022-03-22 17:45 UTC, gilvian commented
> It should be noted that this requires 32 players to be READIED at round start for the gamemode to occur. Even on high pop that... doesn't really happen that often from my recent memory. Code wise looks good, but this will make either very unlikely to happen. I'd drop it down to maybe I dunno, 18?

No, since both of those are cringe on lowpop.

Xenophage turns at least 6 people into benos leaving 12 onboard
Crossfire requiring 14 was "hey 10 get turned into agents" and on lowpop it was just 5 people on ship, 3 civilians and 1 normal officer and it just encouraged TDM.

Carl even stated himself on the discord buffing some of the gamemodes into more should be done since both games are really bad lowpop, and only then they get rolled

2022-03-22 17:57 UTC, Anton-Kr commented
You are failing to see my point that even on high pop there is very rarely 32 people readied. This essentially removes this from existing.

2022-03-22 17:58 UTC, Anton-Kr requested changes
make number less high

2022-03-22 17:58 UTC, gilvian commented
> make number less high

no

2022-03-22 17:58 UTC, gilvian commented
over the sunday we got 30 people ready on the server, it is possible for those gamemodes to exist and not be just a TDM gamemodes with actual roleplay

2022-03-22 18:03 UTC, Anton-Kr commented
I'll let other maintainers weigh in on this.

2022-03-27 00:08 UTC, Anton-Kr commented
As no other maintainers have at this point weighed in, I will be closing this PR as requested changes were not made, and the author does not intend to make them.

2022-03-27 00:08 UTC, closed without merging