Admins can now see sensor stuff
BoHBranch/BoH-Bay pull request #1649
Opened 2022-03-23 17:08 UTC by Cupax3

## About The Pull Request
Haha inefficient indexing go brrrrrr

## Why It's Good For The Game
Admins go brrrrrr

## Did You Test It?
Yep! I hate collapsibles so

![Screenshot_29](https://user-images.githubusercontent.com/5896309/159755929-18e99efb-b8c3-4225-91a7-a18d5fc9cc7b.png)

![Screenshot_30](https://user-images.githubusercontent.com/5896309/159755995-9ea9fcd6-46fe-4a82-94f4-3bd8c3fe8265.png)

The runtimes are unrelated

## Authorship
Me, using code from shuttlesys for indexing

## Changelog

:cl:
admin: Haha Star Map go brrrr
/:cl:

2022-03-23 17:12 UTC, Cupax3 commented
![Screenshot_31](https://user-images.githubusercontent.com/5896309/159757015-98301a72-c9cd-4680-8faf-40a348e73147.png)

Just to show that the runtimes are **really** unrelated

2022-03-23 19:01 UTC, Anton-Kr requested changes, later dismissed

2022-03-23 19:01 UTC, Anton-Kr commented on code/modules/admin/verbs/randomverbs.dm
> +/client/proc/reveal_sensor_map()
I'd prefer this be a toggle so we don't keep cluttering up admin verbs

2022-03-23 19:07 UTC, Cupax3 commented on code/modules/admin/verbs/randomverbs.dm
> +/client/proc/reveal_sensor_map()
A toggle would involve tacking it into the pref system or adding even more variables to the client or wherever we'd store the flag. Unless you want to have it as a toggle in the proc itself by detecting the overmaps, which is not possible in a reasonable way, honestly.

2022-03-23 19:09 UTC, Anton-Kr commented on code/modules/admin/verbs/randomverbs.dm
> +/client/proc/reveal_sensor_map()
ughhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

2022-03-23 19:09 UTC, Anton-Kr approved these changes

2022-03-24 02:25 UTC, Kaksisilma commented
🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵 🥵

2022-03-24 06:04 UTC, merged