Commissary remap
BoHBranch/BoH-Bay pull request #1661
Opened 2022-03-25 10:03 UTC by Don2137

## About The Pull Request
I swapped the Commissary with the Auxiliary Infirmary and made it somewhat bigger. Auxinf also gets a bootleg chem setup. That's about it.

Previous PR was completely wrong on top of having map issues, now everything should be fine
## Why It's Good For The Game
RP areas are always good.
## Did You Test It?
Yes
## Authorship
me
## Changelog

:cl:
maptweak: Remapped the Commissary and the Auxiliary Infirmary
/:cl:

2022-03-26 07:30 UTC, Anton-Kr commented
Large amount of changed lines is indicative of having not run map merger. Contact qqqq on discord if assistance is needed with the process.

2022-03-26 07:30 UTC, Anton-Kr requested changes
Run map merger

2022-03-26 21:32 UTC, Anton-Kr commented
I think the original intent was for traders to use commissary which is why they are next to each other, but ehh I haven't seen that be used much. If checks are good, this should be approved.

2022-03-26 22:23 UTC, Don2137 commented
Unsure why this is failing

2022-03-26 23:39 UTC, Anton-Kr commented
```
[02:00:00] Runtime in code/game/machinery/embedded_controller/docking_program.dm,69: Docking controller tag admin_shuttle_dock_airlock had multiple associated programs.
  proc name: crash at (/proc/crash_at)
  src: null
  call stack:
  crash at("Docking controller tag admin_s...", "code/game/machinery/embedded_c...", 69)
  /datum/computer/file/embedded_... (/datum/computer/file/embedded_program/docking/airlock): New(the docking port controller (/obj/machinery/embedded_controller/radio/airlock/docking_port))
  /datum/computer/file/embedded_... (/datum/computer/file/embedded_program/docking/airlock): New(the docking port controller (/obj/machinery/embedded_controller/radio/airlock/docking_port))
  the docking port controller (/obj/machinery/embedded_controller/radio/airlock/docking_port): Initialize(1)
  the docking port controller (/obj/machinery/embedded_controller/radio/airlock/docking_port): Initialize(1)
  the docking port controller (/obj/machinery/embedded_controller/radio/airlock/docking_port): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the docking port controller (/obj/machinery/embedded_controller/radio/airlock/docking_port), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms()
  Atoms (/datum/controller/subsystem/atoms): Initialize(795478)
  Atoms (/datum/controller/subsystem/atoms): DoInitialize(795478)
  Master (/datum/controller/master): Initialize(10, 0)
```

Not sure if you touched airlocks here but that's the likely issue. If you cannot find it bug me tomorrow and I'll have a look personally.

2022-03-27 20:02 UTC, Don2137 commented
Didn't touch that docking port, no idea what's wrong. Map looks fine too.

2022-03-28 19:23 UTC, Anton-Kr commented
I'll take a look tomorrow or in two days to help you resolve the issue. Please feel free to ping me if (more likely when) I forget.

2022-03-30 08:06 UTC, Rafflesia7793 commented
If the commissary was touched there's a decent chance the docking controller next to it got clipped: 
![image](https://user-images.githubusercontent.com/100093914/160782993-969302ac-65e7-4755-a2e3-40189c7939a0.png)

2022-03-30 09:30 UTC, Don2137 commented
> If the commissary was touched there's a decent chance the docking controller next to it got clipped: ![image](https://user-images.githubusercontent.com/100093914/160782993-969302ac-65e7-4755-a2e3-40189c7939a0.png)

This one is fine, it's the aft starboard one that's runtiming.

2022-04-02 21:14 UTC, Rafflesia7793 commented
Might be related but the Docking Controller inside the airlock next to the commissary is configured for the airlock that's now throwing errors:
![image](https://user-images.githubusercontent.com/100093914/161401433-66c40c2e-c8a1-45ef-bfbf-09777786de39.png)
Admin Shuttle is the Aft Starboard airlock. This is the fore starboard which is usually labelled merchant shuttle.

2022-04-02 21:26 UTC, Rafflesia7793 commented on maps/torch/torch2_deck4.dmm
> +	},
This is what's causing your testing failure currently.

2022-10-12 11:30 UTC, closed without merging