Buffs shields.
BoHBranch/BoH-Bay pull request #1670
Opened 2022-03-26 02:48 UTC by Rafflesia7793

## About The Pull Request
When shields were first introduced and these values set, you could accurately fire longarms while holding one. This is no longer the case, and a result, they have fallen into disuse, only used for the rule of cool. This PR slightly buffs the combat shield's block chance, the amount of damage it is capable of blocking, and moves the shield's slowdown to match it's current capabilities.

## Why It's Good For The Game
Adds more options to the stale combat meta.

## Did You Test It?
Yes.
## Authorship
Rafflesia
## Changelog

2022-03-26 22:31 UTC, Anton-Kr commented
Seems like an interesting change that should make SMGs etc a bit more used/useful. Why not!

2022-03-26 22:31 UTC, Anton-Kr approved these changes

2022-03-26 22:49 UTC, BurpleBineapple commented
> Seems like an interesting change that should make SMGs etc a bit more used/useful. Why not!

SMGs are one handed, at least the 7mm ones available to security. This however will allow you to fire bulldogs and LMGs such with a shield which I'm not sure is a great idea. The plasteel combat shield can projectiles up to AMRs and Fletchette rifles.

2022-03-26 23:09 UTC, Rafflesia7793 commented
>This however will allow you to fire bulldogs and LMGs such with a shield which I'm not sure is a great idea. 

This PR makes zero changes to what weapons can and cannot be fired accurately with the shield in offhand.

2022-03-26 23:23 UTC, Anton-Kr commented
I'll test this a bit further.

2022-03-26 23:35 UTC, Anton-Kr requested changes
Following discussion, this seems a bit heavyhanded. I am fine with removing the slowdown, **OR** upping the block chance rate. I want the max_block however to remain where it is, to make more weapons have the ability to pen the shield, because at the moment even the Skrell railgun wouldn't penetrate the shield.

2022-03-26 23:44 UTC, Rafflesia7793 commented
> Following discussion, this seems a bit heavyhanded. I am fine with removing the slowdown, **OR** upping the block chance rate. I want the max_block however to remain where it is, to make more weapons have the ability to pen the shield, because at the moment even the Skrell railgun wouldn't penetrate the shield.

Considering it's a defensive implement I'll go with making the block chance not nearly 50/50. In the future I'd like to make it so that aiming for feet/hands/head mitigates the shield entirely, hopefully when that happens, we can consider improving the slowdown.

2022-03-27 00:05 UTC, Anton-Kr commented
Apologies if my comment was ambiguous, but I'd still like `max_block `at 50 to allow high caliber weapons outside of just the AMR to penetrate. 

Thanks!

2022-03-27 00:42 UTC, Rafflesia7793 commented
> Apologies if my comment was ambiguous, but I'd still like `max_block `at 50 to allow high caliber weapons outside of just the AMR to penetrate.
> 
> Thanks!

Dafuq? That was unintentional change. I'll fix it again. Probably something with github.

2022-03-27 00:46 UTC, Rafflesia7793 commented
Should be good to go now.

2022-03-27 02:04 UTC, Anton-Kr approved these changes

2022-03-27 05:21 UTC, merged