Adds sutures+inside kits
BoHBranch/BoH-Bay pull request #1682
Opened 2022-03-27 20:08 UTC by Pariah919

## About The Pull Request
Carl said he couldn't be bothered to fix #1657 without cutting it up in the first place, so I asked if I could just atomize it a bit for him.

>Sutures fully added, taking them directly from a PR of MJP's, with his permission. You use these to seal up wounds that have arterial bleeding, without surgery required. You can find these in advanced first aid kits, combat kits and surgical kits. This permits the Combat Medic to do in field wound closing.
>
Medkits buffed a bit, advanced kits hold a bit more to accmodate sutures fitting in them.
## Why It's Good For The Game
Sutures make medical more item based and time based than just giving man bicard until full hp, they add an interesting tradeoff since time is everything in brainmed/ss13.
~~also arteries are so nonthreatning since you can just put a banaid on them and they clear up in like, 5 mintues so...~~
## Did You Test It?
I did.
## Authorship
Carl#2223 for the FAK stuff, MJP#4043, Dudeman100-Ckey
## Changelog

:cl:
add:sutures, sutures in kits.
balance:AFAKs and CFAKs hold a bit more.
/:cl:

2022-03-30 05:42 UTC, Anton-Kr requested changes

2022-03-30 05:42 UTC, Anton-Kr commented on code/game/objects/items/weapons/surgery_tools.dm
> +			playsound(src, 'sound/weapons/suture.ogg', 50, FALSE)
Needs pain here

2022-03-30 05:42 UTC, Anton-Kr commented on code/game/objects/items/weapons/surgery_tools.dm
> +					H.custom_pain("The pain in your [affected.name] is unbearable!",rand(50, 65),affecting = affected)
Honestly this needs to go up way more. I managed to do serious damage to myself and self suture without much in the way of paincrit occuring.

2022-03-30 05:42 UTC, Anton-Kr commented on code/game/objects/items/weapons/surgery_tools.dm
> +/obj/item/weapon/suture
Optional, but I'd prefer this to be a one time use item, with each medkit containing maybe 3-5 or something reasonable.

2022-04-03 11:19 UTC, BurpleBineapple commented
I'm not sure I agree with arteries being treatable without medical skill.

I would prefer if being able to treat arterial wounds was locked behind a check for trained med. If they are not trained in medical, then they cannot fix their arteries, only the external bleeding.

This way it doesn't take work away from medical and allows MTs to have this as a field fix item.

2022-04-03 11:37 UTC, BurpleBineapple requested changes

2022-04-03 11:37 UTC, BurpleBineapple commented on code/game/objects/items/weapons/surgery_tools.dm
> +		if(affected.status & ORGAN_ARTERY_CUT)//Fix arteries first,
```suggestion
		if(affected.status & ORGAN_ARTERY_CUT && user.get_skill_value(SKILL_MEDICAL) == SKILL_ADEPT)//Fix arteries if they are trained in medical.
```

2022-04-03 11:37 UTC, BurpleBineapple commented on code/game/objects/items/weapons/surgery_tools.dm
> +		if(affected.status & ORGAN_ARTERY_CUT)//Fix arteries first,
I would rather you restrict all of this to Trained medical and above.

2022-04-03 11:37 UTC, BurpleBineapple commented on code/game/objects/items/weapons/surgery_tools.dm
> +				if((H == user && prob(75)) || prob(user.skill_fail_chance(SKILL_MEDICAL,50, SKILL_ADEPT)))
```suggestion
				if((H == user && prob(75)) || prob(user.skill_fail_chance(SKILL_MEDICAL,50, SKILL_EXPERT)))
```

2022-04-03 11:37 UTC, BurpleBineapple commented on code/game/objects/items/weapons/surgery_tools.dm
> +				if((H == user && prob(75)) || prob(user.skill_fail_chance(SKILL_MEDICAL,50, SKILL_ADEPT)))
Change the max check to expert for artery fixes, so that it is not guaranteed unless you really know what you're doing as a medical technician.

2022-04-03 11:37 UTC, BurpleBineapple commented on code/game/objects/items/weapons/surgery_tools.dm
> +			if(user.do_skilled(5 SECONDS, SKILL_MEDICAL, H))
```suggestion
			var/delay = 15 * user.skill_delay_mult(SKILL_MEDICAL) //Same delay as CPR
			if(do_after(user, delay, src)
```

2022-04-03 11:38 UTC, BurpleBineapple commented on code/game/objects/items/weapons/surgery_tools.dm
> +			if(user.do_skilled(5 SECONDS, SKILL_MEDICAL, H))
Delay based on how high your medical skill is, same as CPR

2022-04-04 05:39 UTC, BurpleBineapple requested changes

2022-04-04 05:39 UTC, BurpleBineapple commented on code/game/objects/items/weapons/surgery_tools.dm
> +			if(do_after(user, delay, src)
```suggestion
			if(do_after(user, delay, src))
```

2022-04-04 05:39 UTC, BurpleBineapple commented on code/game/objects/items/weapons/surgery_tools.dm
> +			if(do_after(user, delay, src)
Should fix errors. My bad.

2022-04-04 07:12 UTC, BurpleBineapple approved these changes
Approved from me.

2022-04-04 22:45 UTC, merged