rnd/ce buff (advanced tools are back, kind of)
BoHBranch/BoH-Bay pull request #1690
Opened 2022-03-28 09:53 UTC by lolman360

## About The Pull Request

advanced tools. they're more compact than regular tools, look cooler, and in the case of jaws of life, can remove both braces and pry open powered airlocks (after a 7.5s delay)

CE starts with a belt, one starts in CE's locker, and sci can print them. no special materials required yet, but this is subject to change.

advanced welder itemsize large >> normal

## Why It's Good For The Game

bay removed `toolspeed` so until i totally rework the tool system (port neb's or something) the only advantage you get is compactness

## Did You Test It?
not yet

## changelog

:cl:
rscadd: advanced tools
balance: advanced welder now useable
/:cl:

2022-03-28 19:08 UTC, Anton-Kr requested changes

2022-03-28 19:08 UTC, Anton-Kr commented on code/game/objects/items/weapons/tools/screwdriver.dm
> +	w_class = ITEMSIZE_SMALL
```suggestion
	w_class = ITEM_SIZE_SMALL
```

2022-03-30 06:40 UTC, Anton-Kr requested changes

2022-03-30 06:40 UTC, Anton-Kr commented on code/datums/outfits/jobs/engineering.dm
> +	belt = /obj/item/weapon/storage/belt/utility/chief
The toolbelt isn't placed in CE's locker.

2022-03-30 06:40 UTC, Anton-Kr commented on code/game/machinery/doors/airlock.dm
> +			user.visible_message(SPAN_WARNING("[user.name] wedges the [C] into [src] and starts forcing it open!"), SPAN_WARNING("You wedge the [C] into [src] and start forcing it open!"))
I'd prefer this to be destructive in nature (think EMAG) and for it to destroy the airlock.

2022-03-30 06:40 UTC, Anton-Kr commented on code/game/machinery/doors/airlock.dm
> +			if(density)
airlock.dm provides defines here like AIRLOCK_CLOSED and AIRLOCK_OPEN. Please use those instead.

2022-03-30 06:40 UTC, Anton-Kr commented on code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
> +		/obj/item/weapon/storage/belt/utility/chief
Believe the actual locker is defined in Torch files and not here. May be wrong.

2022-03-30 06:41 UTC, Anton-Kr requested changes
RE: Sprites. Both sprites have a very harsh single color outline that isn't very consistent with our (already inconsistent) art style. Could you remove the outline? If not @N8-Toe may be able to assist you.

2022-03-30 07:46 UTC, lolman360 commented on code/game/machinery/doors/airlock.dm
> +			user.visible_message(SPAN_WARNING("[user.name] wedges the [C] into [src] and starts forcing it open!"), SPAN_WARNING("You wedge the [C] into [src] and start forcing it open!"))
ideally it's an engineering tool so i'd like to have it not break airlocks

2022-03-30 07:47 UTC, lolman360 commented on code/datums/outfits/jobs/engineering.dm
> +	belt = /obj/item/weapon/storage/belt/utility/chief
`CE starts with a belt`

2022-03-30 08:07 UTC, BurpleBineapple reviewed
I'd say mostly, I agree with ant here. Code-wise everything works fine, tested that on my local branch.

I don't feel particularly strongly about making the jaws of life break airlocks when prying them open. I think it would be interesting if it could do this to powered airlocks. At the moment, it's just a normal crowbar which is also fine.

2022-03-30 08:07 UTC, BurpleBineapple commented on code/game/machinery/doors/airlock.dm
> +			user.visible_message(SPAN_WARNING("[user.name] wedges the [C] into [src] and starts forcing it open!"), SPAN_WARNING("You wedge the [C] into [src] and start forcing it open!"))
At the moment, this is just acting as a normal crowbar. Destructive might be interesting if it's able to pry open bolted doors.

2022-03-30 23:23 UTC, lolman360 commented on code/game/machinery/doors/airlock.dm
> +			user.visible_message(SPAN_WARNING("[user.name] wedges the [C] into [src] and starts forcing it open!"), SPAN_WARNING("You wedge the [C] into [src] and start forcing it open!"))
> At the moment, this is just acting as a normal crowbar. Destructive might be interesting if it's able to pry open bolted doors.

harm intent is needed to pry open powered doors, i might consider destructive if it can pry open bolted ones too at a longer delay

2022-03-30 23:51 UTC, Anton-Kr commented
@BurpleBineapple it overrides crowbar code for airlocks thus does in fact open powered doors.

2022-10-12 14:49 UTC, closed without merging