Banana pie redux
BoHBranch/BoH-Bay pull request #1720
Opened 2022-03-31 22:34 UTC by Thescri

## About The Pull Request
the return of banana cream pie instead of default snack with banana in

## Why It's Good For The Game
We should at least comment out the pie recipe, otherwise. Nobody likes banana-flavoured default icon snacks.

## Did You Test It?
Recipe tested successfully

## Authorship
Bunnyears

## Changelog

:cl:
tweak: changes banana cream pie desc
bugfix: no more flickering magenta icon in the kitchen
/:cl:

2022-04-03 05:42 UTC, BurpleBineapple requested changes

2022-04-03 05:42 UTC, BurpleBineapple commented on code/modules/reagents/reagent_containers/food/snacks.dm
>  /obj/item/weapon/reagent_containers/food/snacks/bananapie
After looking through the code, this is actually a bug. Instead of changing the recipe's path, please change this to

```suggestion
/obj/item/weapon/reagent_containers/food/snacks/pie
```

This will fix the issue with pies being unable to splat as well.

2022-04-03 05:42 UTC, BurpleBineapple commented on code/modules/cooking/recipes/recipes_oven.dm
> +	result = /obj/item/weapon/reagent_containers/food/snacks/bananapie
```suggestion
	result = /obj/item/weapon/reagent_containers/food/snacks/pie
```
Keep this how it is.

2022-04-03 16:02 UTC, Thescri commented on code/modules/reagents/reagent_containers/food/snacks.dm
>  /obj/item/weapon/reagent_containers/food/snacks/bananapie
Good call. Swapped them around so it should be better now.

2022-04-07 12:16 UTC, BurpleBineapple approved these changes

2022-04-07 12:25 UTC, merged